# Generated by Django 6.0.5 on 2026-05-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('subject', models.CharField(choices=[('Математика', 'Математика'), ('Русский язык', 'Русский язык'), ('Обществознание', 'Обществознание'), ('Физика', 'Физика'), ('Информатика', 'Информатика'), ('Английский язык', 'Английский язык'), ('Химия', 'Химия'), ('Биология', 'Биология'), ('История', 'История'), ('Литература', 'Литература')], max_length=50, verbose_name='Предмет')),
                ('grade', models.CharField(choices=[('9', '9 класс'), ('10', '10 класс'), ('11', '11 класс')], max_length=2, verbose_name='Класс')),
                ('brief', models.TextField(blank=True, verbose_name='Пожелания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('subject', models.CharField(max_length=50, verbose_name='Предмет')),
                ('duration', models.CharField(max_length=50, verbose_name='Длительность')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('subjects', models.CharField(max_length=200, verbose_name='Предметы')),
                ('experience', models.CharField(max_length=50, verbose_name='Опыт')),
                ('bio', models.TextField(verbose_name='Биография')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
    ]
